server:
  port: 9001

spring:
  application:
    name: authserver

issuer:
  url: http://localhost:9001

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG